name: deploy-production

on:
  push:
    branches: [deploy]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deployu to production via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          script: |
            cd ~/cppfolio
            git fetch origin
            git checkout deploy
            git pull origin deploy

            # portfolio production
            docker build -f portfolio/Dockerfile -t cppfolio:latest .
            docker stop cppfolio || true
            docker rm cppfolio || true
            docker run -d \
              --name cppfolio \
              --restart unless-stopped \
              -p 8080:8080 \
              cppfolio:latest

            # blog production
            docker build -f blog/Dockerfile -t cppblog:latest .
            docker stop cppblog || true
            docker rm cppblog || true
            docker run -d \
              --name cppblog \
              --restart unless-stopped \
              -p 8082:8080 \
              cppblog:latest
