name: deploy-staging

on:
  push:
    branches: [testing]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to staging vis SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          script: |
            cd ~/cppfolio
            git fetch origin
            git checkout testing
            git pull origin testing

            # portfolio staging
            docker build -f portfolio/Dockerfile -t cppfolio:staging .
            docker stop cppfolio-staging || true
            docker rm cppfolio-staging || true
            docker run -d \
              --name cppfolio-staging \
              --restart unless-stopped \
              -p 8081:8080 \
              cppfolio:staging

              # blog staging
              docker build -f blog/Dockerfile -t cppblog:staging .
              docker stop cppblog-staging || true
              docker rm cppblog-staging || true
              docker run -d \
                --name cppblog-staging \
                --restart unless-stopped \
                -p 8083:8080 \
                cppblog:staging
